SELECT
	DESA.NAMA_DESA AS NAMA_DESA,
	KH.NAMAKELOMPOK AS NAMA_KELOMPOK,
    KH.NOKONTRAK AS NO_KONTRAK,
    TRN.TGL_TRANSAKSI AS TGL_TRANSAKSI,
    (
		SELECT SUM(LUAS)
        FROM KELOMPOKTANID KD2
        WHERE KD2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS LUAS,
    (
		SELECT SUM(KUANTA_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE TRN2.ID_BAHAN = 1 AND KD2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS QTY_UREA,
    (
		SELECT SUM(KUANTA_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE TRN2.ID_BAHAN = 2 AND KD2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS QTY_TSP,
    (
		SELECT SUM(KUANTA_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE TRN2.ID_BAHAN = 3 AND KD2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS QTY_KCL,
    (
		SELECT SUM(KUANTA_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE KH2.IDKELOMPOK = KH.IDKELOMPOK AND TRN2.ID_BAHAN <> 0
    ) AS QTY_TOTAL,
    (
		SELECT SUM(NILAI_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE TRN2.ID_BIAYA = 1 AND KD2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS BIAYA_ANGKUT,
    (
		SELECT SUM(NILAI_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE TRN2.ID_BIAYA = 2 AND KD2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS BIAYA_MUAT,
    (
		SELECT(
        SELECT SUM(NILAI_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE TRN2.ID_BIAYA = 1 AND KD2.IDKELOMPOK = KH.IDKELOMPOK
        ) + (
        SELECT SUM(NILAI_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE TRN2.ID_BIAYA = 2 AND KD2.IDKELOMPOK = KH.IDKELOMPOK
        )
    ) AS BIAYA_TOTAL,
    TRN.TAHUN_GILING AS TAHUN_GILING
FROM TBL_TRANSAKSI TRN
	INNER JOIN KELOMPOKTANID KD ON TRN.ID_PETANI = KD.IDPETANI
    INNER JOIN KELOMPOKTANIH KH ON KD.IDKELOMPOK = KH.IDKELOMPOK
    INNER JOIN TBL_BAHAN BHN ON BHN.ID_BAHAN = TRN.ID_BAHAN
    INNER JOIN TBL_RELASI_BAHAN_BIAYA R_BHN ON R_BHN.ID_BAHAN = BHN.ID_BAHAN
    INNER JOIN TBL_BIAYA BYA ON BYA.ID_BIAYA = R_BHN.ID_BIAYA
    INNER JOIN TBL_DESA DESA ON KH.ID_DESA = DESA.ID_DESA
WHERE KH.IDAFD = 17 AND (TRN.TGL_TRANSAKSI >= '2018-04-01') AND (TRN.TGL_TRANSAKSI <= '2018-04-30')
GROUP BY KH.IDKELOMPOK
UNION
SELECT
	DESA.NAMA_DESA AS NAMA_DESA,
	KH.NAMAKELOMPOK AS NAMA_KELOMPOK,
    KH.NOKONTRAK AS NO_KONTRAK,
    TRN.TGL_TRANSAKSI AS TGL_TRANSAKSI,
    (
		SELECT SUM(LUAS)
        FROM KELOMPOKTANID KD2
        WHERE KD2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS LUAS,
    (
		SELECT SUM(KUANTA_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE TRN2.ID_BAHAN = 1 AND KD2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS QTY_UREA,
    (
		SELECT SUM(KUANTA_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE TRN2.ID_BAHAN = 2 AND KD2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS QTY_TSP,
    (
		SELECT SUM(KUANTA_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE TRN2.ID_BAHAN = 3 AND KD2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS QTY_KCL,
    (
		SELECT SUM(KUANTA_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE KH2.IDKELOMPOK = KH.IDKELOMPOK AND TRN2.ID_BAHAN <> 0
    ) AS QTY_TOTAL,
    (
		SELECT SUM(NILAI_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE TRN2.ID_BIAYA = 1 AND KD2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS BIAYA_ANGKUT,
    (
		SELECT SUM(NILAI_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE TRN2.ID_BIAYA = 2 AND KD2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS BIAYA_MUAT,
    (
		SELECT(
        SELECT SUM(NILAI_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE TRN2.ID_BIAYA = 1 AND KD2.IDKELOMPOK = KH.IDKELOMPOK
        ) + (
        SELECT SUM(NILAI_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE TRN2.ID_BIAYA = 2 AND KD2.IDKELOMPOK = KH.IDKELOMPOK
        )
    ) AS BIAYA_TOTAL,
    TRN.TAHUN_GILING AS TAHUN_GILING
FROM TBL_TRANSAKSI TRN
	INNER JOIN KELOMPOKTANID KD ON TRN.ID_PETANI = KD.IDPETANI
    INNER JOIN KELOMPOKTANIH KH ON KD.IDKELOMPOK = KH.IDKELOMPOK
    INNER JOIN TBL_BAHAN BHN ON BHN.ID_BAHAN = TRN.ID_BAHAN
    INNER JOIN TBL_RELASI_BAHAN_BIAYA R_BHN ON R_BHN.ID_BAHAN = BHN.ID_BAHAN
    INNER JOIN TBL_BIAYA BYA ON BYA.ID_BIAYA = R_BHN.ID_BIAYA
    INNER JOIN TBL_DESA DESA ON KH.ID_DESA = DESA.ID_DESA
WHERE KH.IDAFD = 17
GROUP BY KH.IDKELOMPOK