SELECT
	KH.NAMAKELOMPOK AS NAMA_KELOMPOK,
    KH.NOKONTRAK AS NO_KONTRAK,
    KH.IDAFD AS ID_AFD,
    (
		SELECT SUM(LUAS) 
        FROM KELOMPOKTANID KD2
			INNER JOIN KELOMPOKTANIH KH2 ON KD2.IDKELOMPOK = KH2.IDKELOMPOK
		WHERE KH2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS TOTAL_LUAS,
	TRN.ID_BIAYA AS ID_BIAYA,
    BYA.NAMA_BIAYA AS NAMA_BIAYA,
    TRN.TGL_TRANSAKSI AS TGL_TRANSAKSI,
    TRN.ID_DOKUMEN AS ID_DOKUMEN,
    SUM(TRN.KUANTA_TRANSAKSI) AS JML_KUANTA,
    (
		SELECT IFNULL((
		SELECT SUM(TRN2.KUANTA_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KH2.IDKELOMPOK = KD2.IDKELOMPOK
        WHERE 
			TRN2.TGL_TRANSAKSI < TRN.TGL_TRANSAKSI
            AND KH2.IDKELOMPOK = KH.IDKELOMPOK
            AND TRN2.ID_BAHAN = 0 
			AND BYA.NAMA_BIAYA <> 'ANGKUT PUPUK'
			AND BYA.NAMA_BIAYA <> 'MUAT DAN BONGKAR PUPUK'),0)
    ) AS JML_KUANTA_LAST,
    (
		SELECT IFNULL((
        SELECT SUM(TRN2.NILAI_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KH2.IDKELOMPOK = KD2.IDKELOMPOK
            INNER JOIN TBL_BIAYA BYA2 ON BYA2.ID_BIAYA = TRN2.ID_BIAYA
            LEFT OUTER JOIN TBL_RELASI_BAHAN_BIAYA REL2 ON TRN2.ID_BIAYA = REL2.ID_BIAYA
        WHERE 
			TRN2.TGL_TRANSAKSI < TRN.TGL_TRANSAKSI
            AND KH2.IDKELOMPOK = KH.IDKELOMPOK
            AND TRN2.ID_BAHAN = 0 
			AND REL2.ID_BIAYA IS NULL),0)
    ) AS JML_NILAI_LAST,
    (
		SELECT SUM(TRN2.NILAI_TRANSAKSI)
        FROM TBL_TRANSAKSI TRN2
			INNER JOIN KELOMPOKTANID KD2 ON TRN2.ID_PETANI = KD2.IDPETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KH2.IDKELOMPOK = KD2.IDKELOMPOK
            INNER JOIN TBL_BIAYA BYA2 ON BYA2.ID_BIAYA = TRN2.ID_BIAYA
            LEFT OUTER JOIN TBL_RELASI_BAHAN_BIAYA REL2 ON TRN2.ID_BIAYA = REL2.ID_BIAYA
        WHERE 
            KH2.IDKELOMPOK = KH.IDKELOMPOK
            AND TRN2.ID_BAHAN = 0 
			AND REL2.ID_BIAYA IS NULL
    ) AS JML_NILAI_SD,
    BYA.SATUAN AS SATUAN,
    BYA.BIAYA AS HARGA_SATUAN,
    SUM(TRN.NILAI_TRANSAKSI) AS JML_NILAI,
    AFD.NAMAASISTEN AS NAMA_ASISTEN,
    SIST.ASKEP_TR AS ASKEP_TR,
    SIST.MANAJER_KEBUN AS MANAJER_KEBUN
FROM
	TBL_TRANSAKSI TRN
    INNER JOIN KELOMPOKTANID KD ON KD.IDPETANI = TRN.ID_PETANI
    INNER JOIN KELOMPOKTANIH KH ON KH.IDKELOMPOK = KD.IDKELOMPOK
    INNER JOIN TBL_BIAYA BYA ON BYA.ID_BIAYA = TRN.ID_BIAYA
    INNER JOIN AFDELING AFD ON KH.IDAFD = AFD.IDAFD
    INNER JOIN TBL_SISTEM SIST ON SIST.TAHUN_GILING = TRN.TAHUN_GILING
    LEFT OUTER JOIN TBL_RELASI_BAHAN_BIAYA REL ON TRN.ID_BIAYA = REL.ID_BIAYA
WHERE
	KH.IDKELOMPOK = '17001'
    AND TRN.ID_BAHAN = 0 
    AND REL.ID_BIAYA IS NULL
    AND TRN.ID_DOKUMEN = 'RDKK-17001'
GROUP BY
	TRN.ID_BIAYA