SELECT
	DESA.NAMA_DESA AS NAMA_DESA,
	KH.NAMAKELOMPOK AS NAMA_KELOMPOK,
    KH.NOKONTRAK AS NO_KONTRAK,
    TRN.TGL_TRANSAKSI AS TGL_TRANSAKSI,
    (
		SELECT SUM(LUAS) 
        FROM KELOMPOKTANID KD2 
        WHERE KD2.IDKELOMPOK = KD.IDKELOMPOK
    ) AS LUAS,
    (
		SELECT SUM(KUANTA_TRANSAKSI) 
        FROM TBL_TRANSAKSI_PUPUK TRN2 
			INNER JOIN KELOMPOKTANID KD2 ON KD2.IDPETANI = TRN2.ID_PETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KH2.IDKELOMPOK = KD2.IDKELOMPOK
        WHERE TRN2.ID_BAHAN = 1 AND KH2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS QTY_UREA,
    (
		SELECT SUM(KUANTA_TRANSAKSI) 
        FROM TBL_TRANSAKSI_PUPUK TRN2 
			INNER JOIN KELOMPOKTANID KD2 ON KD2.IDPETANI = TRN2.ID_PETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KH2.IDKELOMPOK = KD2.IDKELOMPOK
        WHERE TRN2.ID_BAHAN = 2 AND KH2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS QTY_TSP,
    (
		SELECT SUM(KUANTA_TRANSAKSI) 
        FROM TBL_TRANSAKSI_PUPUK TRN2 
			INNER JOIN KELOMPOKTANID KD2 ON KD2.IDPETANI = TRN2.ID_PETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KH2.IDKELOMPOK = KD2.IDKELOMPOK
        WHERE TRN2.ID_BAHAN = 3 AND KH2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS QTY_KCL,
    (
		SELECT SUM(KUANTA_TRANSAKSI) 
        FROM TBL_TRANSAKSI_PUPUK TRN2 
			INNER JOIN KELOMPOKTANID KD2 ON KD2.IDPETANI = TRN2.ID_PETANI
            INNER JOIN KELOMPOKTANIH KH2 ON KH2.IDKELOMPOK = KD2.IDKELOMPOK
        WHERE KH2.IDKELOMPOK = KH.IDKELOMPOK
    ) AS QTY_TOTAL,
    (
		SELECT (
			(SELECT SUM(KUANTA_TRANSAKSI) AS KUANTA_TOTAL
			FROM TBL_TRANSAKSI_PUPUK TRN2 
				INNER JOIN KELOMPOKTANID KD2 ON KD2.IDPETANI = TRN2.ID_PETANI
				INNER JOIN KELOMPOKTANIH KH2 ON KH2.IDKELOMPOK = KD2.IDKELOMPOK
			WHERE KH2.IDKELOMPOK = KH.IDKELOMPOK
            ) * (
				SELECT BYA2.BIAYA
                FROM TBL_BIAYA BYA2
                WHERE BYA2.ID_BIAYA = 1
            )
        )
    ) AS BIAYA_ANGKUT,
    (
		SELECT (
			(SELECT SUM(KUANTA_TRANSAKSI) AS KUANTA_TOTAL
			FROM TBL_TRANSAKSI_PUPUK TRN2 
				INNER JOIN KELOMPOKTANID KD2 ON KD2.IDPETANI = TRN2.ID_PETANI
				INNER JOIN KELOMPOKTANIH KH2 ON KH2.IDKELOMPOK = KD2.IDKELOMPOK
			WHERE KH2.IDKELOMPOK = KH.IDKELOMPOK
            ) * (
				SELECT BYA2.BIAYA
                FROM TBL_BIAYA BYA2
                WHERE BYA2.ID_BIAYA = 2
            )
        )
    ) AS BIAYA_MUAT_BONGKAR,
    (
		SELECT (
			(SELECT SUM(KUANTA_TRANSAKSI) AS KUANTA_TOTAL
			FROM TBL_TRANSAKSI_PUPUK TRN2 
				INNER JOIN KELOMPOKTANID KD2 ON KD2.IDPETANI = TRN2.ID_PETANI
				INNER JOIN KELOMPOKTANIH KH2 ON KH2.IDKELOMPOK = KD2.IDKELOMPOK
			WHERE KH2.IDKELOMPOK = KH.IDKELOMPOK
            ) * (
				SELECT BYA2.BIAYA
                FROM TBL_BIAYA BYA2
                WHERE BYA2.ID_BIAYA = 1
            )
        ) +
			(SELECT SUM(KUANTA_TRANSAKSI) AS KUANTA_TOTAL
			FROM TBL_TRANSAKSI_PUPUK TRN2 
				INNER JOIN KELOMPOKTANID KD2 ON KD2.IDPETANI = TRN2.ID_PETANI
				INNER JOIN KELOMPOKTANIH KH2 ON KH2.IDKELOMPOK = KD2.IDKELOMPOK
			WHERE KH2.IDKELOMPOK = KH.IDKELOMPOK
            ) * (
				SELECT BYA2.BIAYA
                FROM TBL_BIAYA BYA2
                WHERE BYA2.ID_BIAYA = 2
            )
    ) AS BIAYA_TOTAL
FROM TBL_TRANSAKSI_PUPUK TRN
	INNER JOIN KELOMPOKTANID KD ON TRN.ID_PETANI = KD.IDPETANI
    INNER JOIN KELOMPOKTANIH KH ON KD.IDKELOMPOK = KH.IDKELOMPOK
    INNER JOIN TBL_BAHAN BHN ON BHN.ID_BAHAN = TRN.ID_BAHAN
    INNER JOIN TBL_RELASI_BAHAN_BIAYA R_BHN ON R_BHN.ID_BAHAN = BHN.ID_BAHAN
    INNER JOIN TBL_BIAYA BYA ON BYA.ID_BIAYA = R_BHN.ID_BIAYA
    INNER JOIN TBL_DESA DESA ON KH.ID_DESA = DESA.ID_DESA
GROUP BY KH.IDKELOMPOK