SELECT
	KH.NAMAKELOMPOK AS NAMA_KELOMPOK,
    KH.NOKONTRAK AS NO_KONTRAK,
    BYA.NAMA_BIAYA AS NAMA_BIAYA,
    TRN.NILAI_TRANSAKSI AS NILAI_TRANSAKSI
FROM TBL_TRANSAKSI TRN
	INNER JOIN KELOMPOKTANID KD ON TRN.ID_PETANI = KD.IDPETANI
    INNER JOIN KELOMPOKTANIH KH ON KD.IDKELOMPOK = KH.IDKELOMPOK
    INNER JOIN TBL_BIAYA BYA ON BYA.ID_BIAYA = TRN.ID_BIAYA
    LEFT OUTER JOIN TBL_RELASI_BAHAN_BIAYA REL ON TRN.ID_BIAYA = REL.ID_BIAYA
WHERE
    REL.ID_BIAYA IS NULL
    AND TRN.TGL_TRANSAKSI > '2018-03-01' AND TRN.TGL_TRANSAKSI < '2018-04-30'