/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.buma.simtr.view;

import id.buma.simtr.controller.menuController_lama;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Bayu Anandavi Muhardika
 * 
 */

public class MainWindow_lama extends javax.swing.JFrame {
    
    private menuController_lama menuController = new menuController_lama(this);

    /**
     * Creates new form MainWindow
     */
    public MainWindow_lama() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setMenuAction();
        menuController.changeMenuNav("Menu Utama");
    }
    
    public void setMenuAction(){
        pnlMenuAdminTR.addMouseListener(menuController);
        pnlMenuMasterData.addMouseListener(menuController);
        pnlMenuExit.addMouseListener(menuController);
        
        pnlSubMenuLKP.addMouseListener(menuController);
        pnlSubMenuPupuk.addMouseListener(menuController);
        pnlSubMenuPerawatanKebun.addMouseListener(menuController);
        pnlSubMenuTMA.addMouseListener(menuController);
        pnlSubMenuBAST.addMouseListener(menuController);
        pnlSubMenuPBH.addMouseListener(menuController);
        pnlSubMenuAdminTRBack.addMouseListener(menuController);
        pnlWsRDKK.addMouseListener(menuController);
        pnlWsLKP.addMouseListener(menuController);
        pnlSubMenuLKPBack.addMouseListener(menuController);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAtas = new javax.swing.JPanel();
        judulUtama = new javax.swing.JLabel();
        pnlBawah = new javax.swing.JPanel();
        pnlTengah = new javax.swing.JPanel();
        pnlNavigasi = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblLoginDesc = new javax.swing.JLabel();
        lblMenuNav = new javax.swing.JLabel();
        pnlKontainer = new javax.swing.JPanel();
        pnlMenuUtama = new javax.swing.JPanel();
        pnlKontainerMenuUtama = new javax.swing.JPanel();
        pnlMenuAdminTR = new javax.swing.JPanel();
        lblAdminTR = new javax.swing.JLabel();
        pnlMenuMasterData = new javax.swing.JPanel();
        lblMasterData = new javax.swing.JLabel();
        pnlMenuExit = new javax.swing.JPanel();
        lblMenuExit = new javax.swing.JLabel();
        pnlAdminTR = new javax.swing.JPanel();
        pnlKontainerMenuAdminTR = new javax.swing.JPanel();
        pnlSubMenuLKP = new javax.swing.JPanel();
        lblSubMenuLKP = new javax.swing.JLabel();
        pnlSubMenuPupuk = new javax.swing.JPanel();
        lblSubMenuPupuk = new javax.swing.JLabel();
        pnlSubMenuPerawatanKebun = new javax.swing.JPanel();
        lblSubMenuPerawatanKebun = new javax.swing.JLabel();
        pnlSubMenuTMA = new javax.swing.JPanel();
        lblSubMenuTMA = new javax.swing.JLabel();
        pnlSubMenuBAST = new javax.swing.JPanel();
        lblSubMenuBAST = new javax.swing.JLabel();
        pnlSubMenuPBH = new javax.swing.JPanel();
        lblSubMenuPBH = new javax.swing.JLabel();
        pnlSubMenuAdminTRBack = new javax.swing.JPanel();
        lblSubMenuAdminTRBack = new javax.swing.JLabel();
        pnlCrdSubMenuLKP = new javax.swing.JPanel();
        pnlKontainerSubMenuLKP = new javax.swing.JPanel();
        pnlWsRDKK = new javax.swing.JPanel();
        lblWsRDKK = new javax.swing.JLabel();
        pnlWsLKP = new javax.swing.JPanel();
        lblWsLKP = new javax.swing.JLabel();
        pnlSubMenuLKPBack = new javax.swing.JPanel();
        lblSubMenuLKPBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Administrasi Tebu Rakyat");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("frmUtama"); // NOI18N
        setUndecorated(true);

        pnlAtas.setBackground(new java.awt.Color(0, 153, 153));
        pnlAtas.setPreferredSize(new java.awt.Dimension(0, 70));

        judulUtama.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        judulUtama.setForeground(new java.awt.Color(255, 255, 255));
        judulUtama.setText("Sistem Informasi Administrasi Tebu Rakyat");

        javax.swing.GroupLayout pnlAtasLayout = new javax.swing.GroupLayout(pnlAtas);
        pnlAtas.setLayout(pnlAtasLayout);
        pnlAtasLayout.setHorizontalGroup(
            pnlAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(judulUtama)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAtasLayout.setVerticalGroup(
            pnlAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlBawah.setBackground(new java.awt.Color(0, 105, 105));

        javax.swing.GroupLayout pnlBawahLayout = new javax.swing.GroupLayout(pnlBawah);
        pnlBawah.setLayout(pnlBawahLayout);
        pnlBawahLayout.setHorizontalGroup(
            pnlBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBawahLayout.setVerticalGroup(
            pnlBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnlTengah.setBackground(new java.awt.Color(255, 255, 255));

        pnlNavigasi.setBackground(new java.awt.Color(0, 105, 105));
        pnlNavigasi.setPreferredSize(new java.awt.Dimension(72, 30));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsername.setText("Administrator");

        lblLoginDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLoginDesc.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLoginDesc.setText("Anda login sebagai");

        lblMenuNav.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMenuNav.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlNavigasiLayout = new javax.swing.GroupLayout(pnlNavigasi);
        pnlNavigasi.setLayout(pnlNavigasiLayout);
        pnlNavigasiLayout.setHorizontalGroup(
            pnlNavigasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavigasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(242, 242, 242)
                .addComponent(lblLoginDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername)
                .addGap(25, 25, 25))
        );
        pnlNavigasiLayout.setVerticalGroup(
            pnlNavigasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLoginDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMenuNav, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        pnlKontainer.setBackground(new java.awt.Color(255, 255, 255));
        pnlKontainer.setLayout(new java.awt.CardLayout());

        pnlMenuUtama.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuUtama.setName("pnlMenuUtama"); // NOI18N
        pnlMenuUtama.setLayout(new java.awt.GridBagLayout());

        pnlKontainerMenuUtama.setBackground(new java.awt.Color(255, 255, 255));
        pnlKontainerMenuUtama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnlKontainerMenuUtama.setName("pnlKontainerMenuUtama"); // NOI18N
        pnlKontainerMenuUtama.setPreferredSize(new java.awt.Dimension(400, 300));

        pnlMenuAdminTR.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuAdminTR.setName("pnlMenuAdminTR"); // NOI18N
        pnlMenuAdminTR.setPreferredSize(new java.awt.Dimension(140, 140));

        lblAdminTR.setBackground(new java.awt.Color(255, 255, 255));
        lblAdminTR.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAdminTR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminTR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_News_96px.png"))); // NOI18N
        lblAdminTR.setText("Administrasi TR");
        lblAdminTR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAdminTR.setName("lblAdminTR"); // NOI18N
        lblAdminTR.setPreferredSize(new java.awt.Dimension(140, 140));
        lblAdminTR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnlMenuAdminTRLayout = new javax.swing.GroupLayout(pnlMenuAdminTR);
        pnlMenuAdminTR.setLayout(pnlMenuAdminTRLayout);
        pnlMenuAdminTRLayout.setHorizontalGroup(
            pnlMenuAdminTRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuAdminTRLayout.createSequentialGroup()
                .addComponent(lblAdminTR, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMenuAdminTRLayout.setVerticalGroup(
            pnlMenuAdminTRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuAdminTRLayout.createSequentialGroup()
                .addComponent(lblAdminTR, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenuMasterData.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuMasterData.setName("pnlMenuMasterData"); // NOI18N
        pnlMenuMasterData.setPreferredSize(new java.awt.Dimension(140, 140));

        lblMasterData.setBackground(new java.awt.Color(245, 245, 245));
        lblMasterData.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMasterData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMasterData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_Coins_96px.png"))); // NOI18N
        lblMasterData.setText("Pengelolaan Data");
        lblMasterData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblMasterData.setName("lblMasterData"); // NOI18N
        lblMasterData.setPreferredSize(new java.awt.Dimension(140, 140));
        lblMasterData.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnlMenuMasterDataLayout = new javax.swing.GroupLayout(pnlMenuMasterData);
        pnlMenuMasterData.setLayout(pnlMenuMasterDataLayout);
        pnlMenuMasterDataLayout.setHorizontalGroup(
            pnlMenuMasterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuMasterDataLayout.createSequentialGroup()
                .addComponent(lblMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMenuMasterDataLayout.setVerticalGroup(
            pnlMenuMasterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuMasterDataLayout.createSequentialGroup()
                .addComponent(lblMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenuExit.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuExit.setName("pnlMenuExit"); // NOI18N
        pnlMenuExit.setPreferredSize(new java.awt.Dimension(140, 40));

        lblMenuExit.setBackground(new java.awt.Color(255, 255, 255));
        lblMenuExit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMenuExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_Exit_26px.png"))); // NOI18N
        lblMenuExit.setText("Keluar");

        javax.swing.GroupLayout pnlMenuExitLayout = new javax.swing.GroupLayout(pnlMenuExit);
        pnlMenuExit.setLayout(pnlMenuExitLayout);
        pnlMenuExitLayout.setHorizontalGroup(
            pnlMenuExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMenuExit, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        pnlMenuExitLayout.setVerticalGroup(
            pnlMenuExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMenuExit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlKontainerMenuUtamaLayout = new javax.swing.GroupLayout(pnlKontainerMenuUtama);
        pnlKontainerMenuUtama.setLayout(pnlKontainerMenuUtamaLayout);
        pnlKontainerMenuUtamaLayout.setHorizontalGroup(
            pnlKontainerMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKontainerMenuUtamaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pnlMenuAdminTR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(pnlKontainerMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMenuExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlMenuMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        pnlKontainerMenuUtamaLayout.setVerticalGroup(
            pnlKontainerMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKontainerMenuUtamaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlKontainerMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMenuMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlMenuAdminTR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(pnlMenuExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnlMenuUtama.add(pnlKontainerMenuUtama, new java.awt.GridBagConstraints());

        pnlKontainer.add(pnlMenuUtama, "crdMenuUtama");

        pnlAdminTR.setBackground(new java.awt.Color(255, 255, 255));
        pnlAdminTR.setName("pnlAdminTR"); // NOI18N
        pnlAdminTR.setLayout(new java.awt.GridBagLayout());

        pnlKontainerMenuAdminTR.setBackground(new java.awt.Color(255, 255, 255));
        pnlKontainerMenuAdminTR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnlKontainerMenuAdminTR.setPreferredSize(new java.awt.Dimension(600, 400));
        pnlKontainerMenuAdminTR.setRequestFocusEnabled(false);

        pnlSubMenuLKP.setBackground(new java.awt.Color(255, 255, 255));
        pnlSubMenuLKP.setName("pnlSubMenuLKP"); // NOI18N
        pnlSubMenuLKP.setPreferredSize(new java.awt.Dimension(270, 70));

        lblSubMenuLKP.setBackground(new java.awt.Color(255, 255, 255));
        lblSubMenuLKP.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSubMenuLKP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_Document_52px.png"))); // NOI18N
        lblSubMenuLKP.setText("Laporan Kemajuan Pekerjaan");
        lblSubMenuLKP.setName(""); // NOI18N

        javax.swing.GroupLayout pnlSubMenuLKPLayout = new javax.swing.GroupLayout(pnlSubMenuLKP);
        pnlSubMenuLKP.setLayout(pnlSubMenuLKPLayout);
        pnlSubMenuLKPLayout.setHorizontalGroup(
            pnlSubMenuLKPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
            .addGroup(pnlSubMenuLKPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSubMenuLKP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
        );
        pnlSubMenuLKPLayout.setVerticalGroup(
            pnlSubMenuLKPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(pnlSubMenuLKPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSubMenuLKP, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
        );

        pnlSubMenuPupuk.setBackground(new java.awt.Color(255, 255, 255));
        pnlSubMenuPupuk.setName("pnlSubMenuPupuk"); // NOI18N
        pnlSubMenuPupuk.setPreferredSize(new java.awt.Dimension(270, 70));

        lblSubMenuPupuk.setBackground(new java.awt.Color(255, 255, 255));
        lblSubMenuPupuk.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSubMenuPupuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_Document_52px.png"))); // NOI18N
        lblSubMenuPupuk.setText("Pemakaian Pupuk");
        lblSubMenuPupuk.setName(""); // NOI18N

        javax.swing.GroupLayout pnlSubMenuPupukLayout = new javax.swing.GroupLayout(pnlSubMenuPupuk);
        pnlSubMenuPupuk.setLayout(pnlSubMenuPupukLayout);
        pnlSubMenuPupukLayout.setHorizontalGroup(
            pnlSubMenuPupukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
            .addGroup(pnlSubMenuPupukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSubMenuPupuk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
        );
        pnlSubMenuPupukLayout.setVerticalGroup(
            pnlSubMenuPupukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(pnlSubMenuPupukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSubMenuPupuk, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        pnlSubMenuPerawatanKebun.setBackground(new java.awt.Color(255, 255, 255));
        pnlSubMenuPerawatanKebun.setName("pnlSubMenuPerawatanKebun"); // NOI18N
        pnlSubMenuPerawatanKebun.setPreferredSize(new java.awt.Dimension(270, 70));

        lblSubMenuPerawatanKebun.setBackground(new java.awt.Color(255, 255, 255));
        lblSubMenuPerawatanKebun.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSubMenuPerawatanKebun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_Document_52px.png"))); // NOI18N
        lblSubMenuPerawatanKebun.setText("Perawatan Kebun");
        lblSubMenuPerawatanKebun.setName(""); // NOI18N

        javax.swing.GroupLayout pnlSubMenuPerawatanKebunLayout = new javax.swing.GroupLayout(pnlSubMenuPerawatanKebun);
        pnlSubMenuPerawatanKebun.setLayout(pnlSubMenuPerawatanKebunLayout);
        pnlSubMenuPerawatanKebunLayout.setHorizontalGroup(
            pnlSubMenuPerawatanKebunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
            .addGroup(pnlSubMenuPerawatanKebunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSubMenuPerawatanKebun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
        );
        pnlSubMenuPerawatanKebunLayout.setVerticalGroup(
            pnlSubMenuPerawatanKebunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(pnlSubMenuPerawatanKebunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSubMenuPerawatanKebun, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
        );

        pnlSubMenuTMA.setBackground(new java.awt.Color(255, 255, 255));
        pnlSubMenuTMA.setName("pnlSubMenuTMA"); // NOI18N
        pnlSubMenuTMA.setPreferredSize(new java.awt.Dimension(270, 70));

        lblSubMenuTMA.setBackground(new java.awt.Color(255, 255, 255));
        lblSubMenuTMA.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSubMenuTMA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_Document_52px.png"))); // NOI18N
        lblSubMenuTMA.setText("Tebang-Muat-Angkut (TMA)");
        lblSubMenuTMA.setName(""); // NOI18N

        javax.swing.GroupLayout pnlSubMenuTMALayout = new javax.swing.GroupLayout(pnlSubMenuTMA);
        pnlSubMenuTMA.setLayout(pnlSubMenuTMALayout);
        pnlSubMenuTMALayout.setHorizontalGroup(
            pnlSubMenuTMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
            .addGroup(pnlSubMenuTMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSubMenuTMA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
        );
        pnlSubMenuTMALayout.setVerticalGroup(
            pnlSubMenuTMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(pnlSubMenuTMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSubMenuTMA, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        pnlSubMenuBAST.setBackground(new java.awt.Color(255, 255, 255));
        pnlSubMenuBAST.setName("pnlSubMenuBAST"); // NOI18N
        pnlSubMenuBAST.setPreferredSize(new java.awt.Dimension(270, 70));

        lblSubMenuBAST.setBackground(new java.awt.Color(255, 255, 255));
        lblSubMenuBAST.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSubMenuBAST.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_Document_52px.png"))); // NOI18N
        lblSubMenuBAST.setText("Berita Acara Selesai Tebang");
        lblSubMenuBAST.setName(""); // NOI18N

        javax.swing.GroupLayout pnlSubMenuBASTLayout = new javax.swing.GroupLayout(pnlSubMenuBAST);
        pnlSubMenuBAST.setLayout(pnlSubMenuBASTLayout);
        pnlSubMenuBASTLayout.setHorizontalGroup(
            pnlSubMenuBASTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
            .addGroup(pnlSubMenuBASTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSubMenuBAST, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
        );
        pnlSubMenuBASTLayout.setVerticalGroup(
            pnlSubMenuBASTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(pnlSubMenuBASTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSubMenuBAST, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        pnlSubMenuPBH.setBackground(new java.awt.Color(255, 255, 255));
        pnlSubMenuPBH.setName("pnlSubMenuPBH"); // NOI18N
        pnlSubMenuPBH.setPreferredSize(new java.awt.Dimension(270, 70));

        lblSubMenuPBH.setBackground(new java.awt.Color(255, 255, 255));
        lblSubMenuPBH.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSubMenuPBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_Document_52px.png"))); // NOI18N
        lblSubMenuPBH.setText("Perhitungan Bagi Hasil");
        lblSubMenuPBH.setName(""); // NOI18N

        javax.swing.GroupLayout pnlSubMenuPBHLayout = new javax.swing.GroupLayout(pnlSubMenuPBH);
        pnlSubMenuPBH.setLayout(pnlSubMenuPBHLayout);
        pnlSubMenuPBHLayout.setHorizontalGroup(
            pnlSubMenuPBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
            .addGroup(pnlSubMenuPBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSubMenuPBH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
        );
        pnlSubMenuPBHLayout.setVerticalGroup(
            pnlSubMenuPBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(pnlSubMenuPBHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSubMenuPBH, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        pnlSubMenuAdminTRBack.setBackground(new java.awt.Color(255, 255, 255));
        pnlSubMenuAdminTRBack.setName("pnlSubMenuAdminTRBack"); // NOI18N
        pnlSubMenuAdminTRBack.setPreferredSize(new java.awt.Dimension(270, 70));

        lblSubMenuAdminTRBack.setBackground(new java.awt.Color(255, 255, 255));
        lblSubMenuAdminTRBack.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSubMenuAdminTRBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubMenuAdminTRBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_Back_Arrow_52px.png"))); // NOI18N
        lblSubMenuAdminTRBack.setText("ke Menu Utama");
        lblSubMenuAdminTRBack.setIconTextGap(12);
        lblSubMenuAdminTRBack.setName(""); // NOI18N

        javax.swing.GroupLayout pnlSubMenuAdminTRBackLayout = new javax.swing.GroupLayout(pnlSubMenuAdminTRBack);
        pnlSubMenuAdminTRBack.setLayout(pnlSubMenuAdminTRBackLayout);
        pnlSubMenuAdminTRBackLayout.setHorizontalGroup(
            pnlSubMenuAdminTRBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlSubMenuAdminTRBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSubMenuAdminTRBack, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
        );
        pnlSubMenuAdminTRBackLayout.setVerticalGroup(
            pnlSubMenuAdminTRBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(pnlSubMenuAdminTRBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSubMenuAdminTRBack, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlKontainerMenuAdminTRLayout = new javax.swing.GroupLayout(pnlKontainerMenuAdminTR);
        pnlKontainerMenuAdminTR.setLayout(pnlKontainerMenuAdminTRLayout);
        pnlKontainerMenuAdminTRLayout.setHorizontalGroup(
            pnlKontainerMenuAdminTRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKontainerMenuAdminTRLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlKontainerMenuAdminTRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKontainerMenuAdminTRLayout.createSequentialGroup()
                        .addComponent(pnlSubMenuPupuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlSubMenuBAST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKontainerMenuAdminTRLayout.createSequentialGroup()
                        .addComponent(pnlSubMenuLKP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(pnlSubMenuPerawatanKebun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKontainerMenuAdminTRLayout.createSequentialGroup()
                        .addComponent(pnlSubMenuTMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlKontainerMenuAdminTRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlSubMenuAdminTRBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlSubMenuPBH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlKontainerMenuAdminTRLayout.setVerticalGroup(
            pnlKontainerMenuAdminTRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKontainerMenuAdminTRLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlKontainerMenuAdminTRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSubMenuLKP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlSubMenuPerawatanKebun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnlKontainerMenuAdminTRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlKontainerMenuAdminTRLayout.createSequentialGroup()
                        .addComponent(pnlSubMenuPupuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(pnlSubMenuTMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKontainerMenuAdminTRLayout.createSequentialGroup()
                        .addComponent(pnlSubMenuBAST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlSubMenuPBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(pnlSubMenuAdminTRBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pnlAdminTR.add(pnlKontainerMenuAdminTR, new java.awt.GridBagConstraints());

        pnlKontainer.add(pnlAdminTR, "crdAdminTR");

        pnlCrdSubMenuLKP.setBackground(new java.awt.Color(255, 255, 255));
        pnlCrdSubMenuLKP.setLayout(new java.awt.GridBagLayout());

        pnlKontainerSubMenuLKP.setBackground(new java.awt.Color(255, 255, 255));
        pnlKontainerSubMenuLKP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnlKontainerSubMenuLKP.setPreferredSize(new java.awt.Dimension(600, 400));

        pnlWsRDKK.setBackground(new java.awt.Color(255, 255, 255));
        pnlWsRDKK.setName("pnlWsRDKK"); // NOI18N
        pnlWsRDKK.setPreferredSize(new java.awt.Dimension(250, 40));

        lblWsRDKK.setBackground(new java.awt.Color(255, 255, 255));
        lblWsRDKK.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblWsRDKK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_List_26px.png"))); // NOI18N
        lblWsRDKK.setText("Kertas Kerja RDKK");
        lblWsRDKK.setName(""); // NOI18N

        javax.swing.GroupLayout pnlWsRDKKLayout = new javax.swing.GroupLayout(pnlWsRDKK);
        pnlWsRDKK.setLayout(pnlWsRDKKLayout);
        pnlWsRDKKLayout.setHorizontalGroup(
            pnlWsRDKKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(pnlWsRDKKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWsRDKKLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblWsRDKK, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
        );
        pnlWsRDKKLayout.setVerticalGroup(
            pnlWsRDKKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(pnlWsRDKKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblWsRDKK, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
        );

        pnlWsLKP.setBackground(new java.awt.Color(255, 255, 255));
        pnlWsLKP.setName("pnlWsLKP"); // NOI18N
        pnlWsLKP.setPreferredSize(new java.awt.Dimension(250, 40));

        lblWsLKP.setBackground(new java.awt.Color(255, 255, 255));
        lblWsLKP.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblWsLKP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_List_26px.png"))); // NOI18N
        lblWsLKP.setText("Kertas Kerja LKP");
        lblWsLKP.setName(""); // NOI18N

        javax.swing.GroupLayout pnlWsLKPLayout = new javax.swing.GroupLayout(pnlWsLKP);
        pnlWsLKP.setLayout(pnlWsLKPLayout);
        pnlWsLKPLayout.setHorizontalGroup(
            pnlWsLKPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(pnlWsLKPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWsLKPLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblWsLKP, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
        );
        pnlWsLKPLayout.setVerticalGroup(
            pnlWsLKPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(pnlWsLKPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblWsLKP, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
        );

        pnlSubMenuLKPBack.setBackground(new java.awt.Color(255, 255, 255));
        pnlSubMenuLKPBack.setName("pnlSubMenuLKPBack"); // NOI18N
        pnlSubMenuLKPBack.setPreferredSize(new java.awt.Dimension(250, 40));

        lblSubMenuLKPBack.setBackground(new java.awt.Color(255, 255, 255));
        lblSubMenuLKPBack.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSubMenuLKPBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_Back_Arrow_26px.png"))); // NOI18N
        lblSubMenuLKPBack.setText("ke Menu LKP");
        lblSubMenuLKPBack.setName(""); // NOI18N

        javax.swing.GroupLayout pnlSubMenuLKPBackLayout = new javax.swing.GroupLayout(pnlSubMenuLKPBack);
        pnlSubMenuLKPBack.setLayout(pnlSubMenuLKPBackLayout);
        pnlSubMenuLKPBackLayout.setHorizontalGroup(
            pnlSubMenuLKPBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(pnlSubMenuLKPBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubMenuLKPBackLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblSubMenuLKPBack, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
        );
        pnlSubMenuLKPBackLayout.setVerticalGroup(
            pnlSubMenuLKPBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(pnlSubMenuLKPBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblSubMenuLKPBack, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlKontainerSubMenuLKPLayout = new javax.swing.GroupLayout(pnlKontainerSubMenuLKP);
        pnlKontainerSubMenuLKP.setLayout(pnlKontainerSubMenuLKPLayout);
        pnlKontainerSubMenuLKPLayout.setHorizontalGroup(
            pnlKontainerSubMenuLKPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKontainerSubMenuLKPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKontainerSubMenuLKPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlWsRDKK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlWsLKP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlSubMenuLKPBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        pnlKontainerSubMenuLKPLayout.setVerticalGroup(
            pnlKontainerSubMenuLKPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKontainerSubMenuLKPLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlWsRDKK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlWsLKP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlSubMenuLKPBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        pnlCrdSubMenuLKP.add(pnlKontainerSubMenuLKP, new java.awt.GridBagConstraints());

        pnlKontainer.add(pnlCrdSubMenuLKP, "crdSubMenuLKP");

        javax.swing.GroupLayout pnlTengahLayout = new javax.swing.GroupLayout(pnlTengah);
        pnlTengah.setLayout(pnlTengahLayout);
        pnlTengahLayout.setHorizontalGroup(
            pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNavigasi, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
            .addComponent(pnlKontainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTengahLayout.setVerticalGroup(
            pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTengahLayout.createSequentialGroup()
                .addComponent(pnlNavigasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKontainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlAtas, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
            .addComponent(pnlTengah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTengah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlBawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow_lama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow_lama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow_lama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow_lama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow_lama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel judulUtama;
    private javax.swing.JLabel lblAdminTR;
    private javax.swing.JLabel lblLoginDesc;
    private javax.swing.JLabel lblMasterData;
    private javax.swing.JLabel lblMenuExit;
    private javax.swing.JLabel lblMenuNav;
    private javax.swing.JLabel lblSubMenuAdminTRBack;
    private javax.swing.JLabel lblSubMenuBAST;
    private javax.swing.JLabel lblSubMenuLKP;
    private javax.swing.JLabel lblSubMenuLKPBack;
    private javax.swing.JLabel lblSubMenuPBH;
    private javax.swing.JLabel lblSubMenuPerawatanKebun;
    private javax.swing.JLabel lblSubMenuPupuk;
    private javax.swing.JLabel lblSubMenuTMA;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWsLKP;
    private javax.swing.JLabel lblWsRDKK;
    private javax.swing.JPanel pnlAdminTR;
    private javax.swing.JPanel pnlAtas;
    private javax.swing.JPanel pnlBawah;
    private javax.swing.JPanel pnlCrdSubMenuLKP;
    private javax.swing.JPanel pnlKontainer;
    private javax.swing.JPanel pnlKontainerMenuAdminTR;
    private javax.swing.JPanel pnlKontainerMenuUtama;
    private javax.swing.JPanel pnlKontainerSubMenuLKP;
    private javax.swing.JPanel pnlMenuAdminTR;
    private javax.swing.JPanel pnlMenuExit;
    private javax.swing.JPanel pnlMenuMasterData;
    private javax.swing.JPanel pnlMenuUtama;
    private javax.swing.JPanel pnlNavigasi;
    private javax.swing.JPanel pnlSubMenuAdminTRBack;
    private javax.swing.JPanel pnlSubMenuBAST;
    private javax.swing.JPanel pnlSubMenuLKP;
    private javax.swing.JPanel pnlSubMenuLKPBack;
    private javax.swing.JPanel pnlSubMenuPBH;
    private javax.swing.JPanel pnlSubMenuPerawatanKebun;
    private javax.swing.JPanel pnlSubMenuPupuk;
    private javax.swing.JPanel pnlSubMenuTMA;
    private javax.swing.JPanel pnlTengah;
    private javax.swing.JPanel pnlWsLKP;
    private javax.swing.JPanel pnlWsRDKK;
    // End of variables declaration//GEN-END:variables
    
    public JPanel getPnlKontainer(){
        return pnlKontainer;
    }
    
    public JPanel getPnlRDKK(){
        return pnlAdminTR;
    }
    
    public JLabel getLblMenuNav(){
        return lblMenuNav;
    }
    
    public JLabel getLblAdminTR(){
        return lblAdminTR;
    }
    
    public JLabel getLblMasterData(){
        return lblMasterData;
    }
    
    public JPanel getPnlKontainerMenuAdminTR(){
        return pnlKontainerMenuAdminTR;
    }
    
    public JPanel getPnlKontainerMenuUtama(){
        return pnlKontainerMenuUtama;
    }
    
    public JPanel getPnlMenuMasterData(){
        return pnlMenuMasterData;
    }
    
    public JPanel getPnlMenuAdminTR(){
        return pnlMenuAdminTR;
    }

}
